### ISSUE TITLE
ResponseType_OnFilterSubscribe提示未声明的标识符错误

### ISSUE THREAD

**Issue by kukuwa** [QuantBox/XAPI3#3]
在编译XAPI_CPP项目的时候，显示“ResponseType_OnFilterSubscribe 未声明的标识符错误”ResponseType_OnFilterSubscribe缺少定义。

**Comment by wukan1986** [comment]
感谢指正，已经删除了此段。

意识到接的接口越多，每个接口的特性都不一样，行情与交易还好办，但登录部分就过于灵活，所以将以前的传参的方法改成了传配置文件路径，由每个接口自己内部实现配置加载。
