### ISSUE TITLE
请问新版XAPI_CSharp的配置文件格式是什么？

### ISSUE THREAD

**Issue by zhuce2022** [QuantBox/XAPI3#4]
如代码 languages\XAPI_CSharp\Program.cs第127行所示：
`      api.Connect(
                @"d:\Users\Kan\Documents\GitHub\XAPI3\bin\Debug64\x64\CTP_SE\md_1.json",
                @"d:\Users\Kan\Documents\GitHub\XAPI3\bin\Debug64\x64\CTP_SE\md_2.json",
                Path.GetTempPath());`

请问伍老师 md_1.json、md_2.json和td_1.json、td_2.json格式是怎么样的呢？谢谢

**Comment by wukan1986** [comment]
文件不存在时会自动生成
